<?php
/**
 * @author Nathaniel Rogers <nathaniel.s.rogers+dev@gmail.com>
 */

namespace ${NAMESPACE} ;

/**
 * Class ${CLASS}
 * @package ${NAMESPACE}
 */
class ${CLASS} extends \PHPUnit\Framework\TestCase {

    /**
     * Do basic setup stuff
     */
    protected function setUp(): void
    {
        ${DS}this->objectManager = new \Magento\Framework\TestFramework\Unit\Helper\ObjectManager(${DS}this);

    }

    public function testThing() {
        ${DS}this->assertEquals(true, ${DS}this->_mock->thisToTest(), 'Autogenerated test: write unit tests');
    }

}
